### ISSUE TITLE
[BUG] Segmentation fault - h5py

### ISSUE THREAD

**Issue by AlexandreF-1qbit** [goodchemistryco/Tangelo#258]
# Issue: Bug Report

**Current Behavior**
Computation of RDMS with CCSD raises an error:
```python
Exception ignored in: <function H5TmpFile.__del__ at 0x7fd655bf93a0>
Traceback (most recent call last):
  File "/home/alex/VirtEnvs/qsdk/lib/python3.8/site-packages/pyscf/lib/misc.py", line 1004, in __del__
    self.close()
  File "/home/alex/VirtEnvs/qsdk/lib/python3.8/site-packages/h5py/_hl/files.py", line 552, in close
    self.id._close_open_objects(h5f.OBJ_LOCAL | h5f.OBJ_FILE)
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5f.pyx", line 360, in h5py.h5f.FileID._close_open_objects
RuntimeError: Can't decrement id ref count (unable to extend file properly, errno = 2, error message = 'No such file or directory')
Segmentation fault (core dumped)
```

It may be related to [pyscf config](https://github.com/pyscf/pyscf/blob/655e237f73d64b4371fb9bf4679b3b24747ef5c5/pyscf/__config__.py#L11-L12) and [h5py temporary file close method](https://github.com/pyscf/pyscf/blob/91ff78377d6cc5c4b062051b4846df1c1ffd4a7c/pyscf/lib/misc.py#L1004).

**Steps to Reproduce (minimal example)**
1. Create a new python environment.
2. Install tangelo (`pip install tangelo-gc`).
3. Compute the RDMs (with `CCSDSolver`) of any molecule (call the `f = lib.H5TmpFile()` line).

**Environment**
Virtual machine, Ubuntu 22.04.1 LTS (GNU/Linux 5.15.0-56-generic x86_64)
```
Summary of the h5py configuration
---------------------------------

h5py    3.7.0
HDF5    1.12.2
Python  3.8.15 (default, Dec  6 2022, 10:28:26)
[GCC 11.3.0]
sys.platform    linux
sys.maxsize     9223372036854775807
numpy   1.23.5
cython (built with) 0.29.30
numpy (built against) 1.17.3
HDF5 (built against) 1.12.2
```
I'm also getting the same error with pythons>=3.7, h5py>=2.8.

**Possible Solution**
(Temporary workaround) Setting the `TMPDIR` or the `PYSCF_TMPDIR` environment variables to `/tmp` help preventing the error. By default, PySCF set the scratch path as `.` when `TMPDIR` is not set. However, the H5 libraries does not seem to play well with relative paths.

**Comment by ValentinS4t1qbit** [comment]
This seems related to pyscf and h5py: is there anything wrong with tangelo's code itself, do we need to do anything about this ?

If not, what do we expect from this Github issue ?

**Comment by AlexandreF-1qbit** [comment]
This problem is not reported on the pyscf repo: it might be due the code specific in Tangelo (calling the `f = lib.H5TmpFile()` line without the environment variable set). I can try to see if the problem persists now, and I will close this issue if not.

**Comment by AlexandreF-1qbit** [comment]
With the last release, I am not getting this error.
