### ISSUE TITLE
Documentation inconsistencies / small fixes

### ISSUE THREAD

**Issue by alexfleury-sb** [goodchemistryco/Tangelo#259]
Here is a list where I am keeping documentation inconsistencies / small fixes in Tangelo. Before the next release, we could fix them all at once.

- The Pauli strings are reversed in (code is correct) https://github.com/goodchemistryco/Tangelo/blob/f4d46ad0a5bb6c10b456e1d24dc8d8c8546837e7/tangelo/toolboxes/qubit_mappings/hcb.py#L67-L69
- lauren -> laurent
https://github.com/goodchemistryco/Tangelo/blob/5d3e9da841550dd30ebefd6c7f7d6abba5785930/tangelo/toolboxes/circuits/qsp.py#L49
- It is not a pyscf molecule.
https://github.com/goodchemistryco/Tangelo/blob/3559208427fb2eb55c5be53b1480f10b8f7008ca/tangelo/algorithms/variational/adapt_vqe_solver.py#L138

**Comment by ValentinS4t1qbit** [comment]
Please don't hesitate to push this to the finish line and close it so that we don't keep items in flight if we can get rid of them and focus on other things.

**Comment by AlexandreF-1qbit** [comment]
Yes, it can be closed with #272.
