### ISSUE TITLE
[FEATURE REQUEST] <Frozen Core / Active Space in DMET>

### ISSUE THREAD

**Issue by chrislzhao** [goodchemistryco/Tangelo#270]
# Issue: Feature Request

**What problem does this feature request help you overcome? Please describe.**
In the DMET problem decomposition, after the bath orbitals are created and the dummy molecule is constructed and passed to the solver, I would like to have an option of frozen core / selection of active spaces, as this will reduce the computational complexity of the solver, especially VQE when you run it on small hardware devices. 

**Describe the solution you'd like**
In the DMET options, provide a new option that set the frozen orbitals for each fragment.

**Comment by AlexandreF-1qbit** [comment]
Hi @chrislzhao, the Good Chemistry team talked about implementing that in the past, but we got side-tracked with other priorities. We will take a look at implementing this as it seems important to you! We may ask for your feedbacks if we have different ideas on the user interface / implementation, only if this is OK with you.

**Comment by chrislzhao** [comment]
Hi @AlexandreF-1qbit Thanks for getting back to me! It's good to hear that you have this on your plate, and I will be more than happy to provide feedbacks.

**Comment by AlexandreF-1qbit** [comment]
Hello @chrislzhao, I feel the need of providing updates. Here they are:
- The construction of smaller `SecondQuantizedDMETFragment` with frozen orbitals is mostly done. I work in this fork/branch: https://github.com/AlexandreF-1qbit/Tangelo/tree/frozen_orbs_dmet.
- The interface I was thinking of at first is by passing a "fragment_frozen_orbitals" entry to the DMET option dictionary. The input would consist of a list of n elements, where n is the number of fragments. Each element could be an integer (first n orbitals to be frozen) and a list of integers (corresponding to orbital indices).
- At the moment, I am still trying to figure out how to fix the number of electrons computation (traces of 1-RDMs) with those frozen degrees of freedom. I'll try to reach out to internal resources to see if some people have insights on this.

**Comment by AlexandreF-1qbit** [comment]
PR #276 has been opened for this issue.

**Comment by chrislzhao** [comment]
Thank you so much for it! Is the PR ready for testing?

**Comment by AlexandreF-1qbit** [comment]
Yes! It should be up to testing by providing the `fragment_frozen_orbitals` option to the DMET dictionary.

**Comment by ValentinS4t1qbit** [comment]
@chrislzhao We have merged this PR into the main branch and the new release, but we'll keep the issue open so that you can confirm this is working out for you or if something more needs to happen :)

**Comment by chrislzhao** [comment]
I did some testings and it seems that it is working pretty well.

**Comment by ValentinS4t1qbit** [comment]
Thank you ! Then I will close this feature request for now. Bugs we come across can be brought up in a new "bug" issue :)

**Comment by chrislzhao** [comment]
Sounds good. Thank you!
