### ISSUE TITLE
[IMPROVEMENT] Circuit depth method too slow

### ISSUE THREAD

**Issue by AlexandreF-1qbit** [goodchemistryco/Tangelo#283]
# Circuit depth code

The `tangelo.linq.circuit.depth` method:https://github.com/goodchemistryco/Tangelo/blob/23104ce527d305856bfdd78cf875638409e05c99/tangelo/linq/circuit.py#L196-L221 
is very slow. When dealing with >5-qubit circuit, it is mainly the bottleneck to output resource estimation. 

One way to circumvent this is to use the cirq package (it uses moment during the construction, and it is somehow faster). For e.g.,
```python
from tangelo.molecule_library import mol_H2O_sto3g, mol_H2O_321g
from tangelo.toolboxes.ansatz_generator import UCCSD

mol = mol_H2O_321g

ansatz = UCCSD(mol, mapping="JW")
ansatz.build_circuit()
circuit = ansatz.circuit

circuit.depth()
```
does not output anything in 20 min on my machine. However,
```python
from tangelo.linq import translate_circuit

def depth_from_cirq(circuit):
    cirq_circuit = translate_circuit(circuit, source="tangelo", target="cirq")
    return len(cirq_circuit.moments)

depth_from_cirq(circuit)
```
outputs
```
CPU times: user 8.39 s, sys: 18.7 ms, total: 8.4 s
Wall time: 8.42 s
116869
```

Moreover, printing the depth in resource estimation should be optional.

**Comment by ValentinS4t1qbit** [comment]
When I implemented this function, I had the choice between recomputing depth from scratch or simply storing more data and update that depth when we add a gate, gradually. I suspected that It could have a good impact on performance.

I think that can be a quick and easy path to explore. Since our package has a dependency on Openfermion and thus Cirq, I think your suggestion is still something to consider.

**Comment by AlexandreF-1qbit** [comment]
I agree. The only thing I am concerned is that we prevent the depth measurement of circuit with unsupported gates by cirq. We could try with cirq, and if there is an error we call this function instead 9with a warning).

**Comment by ValentinS4t1qbit** [comment]
Looking into it.

Btw you say "printing depth should be optional for resource estimation". The goal of resource estimation is to get access to interesting quantities and info about the approach quickly without trying to run the whole thing.

If we end up making this depth calculation fast enough, do you still think it should be not be done by default ?

**Comment by ValentinS4t1qbit** [comment]
Ok, this is pretty funny.

I was dumb and doing a manual loop to search for the latest moment the qubits of each gate were encountered. Instead I decided to use a look up dictionary (duh), so basically at no cost in memory I had a ridiculous increase in performance and your use case is now instant.

FYI almost all the time of your cirq suggestion is spent in the translation function. if we discount that, well, I'm already faster than cirq's depth method itself apparently (1.5-2x).

For `mol_H2O_sto3g`:

```
Ansatz circuit build: 3.2853076457977295 s

# Tangelo "depth v2" method
Depth: 116868
Runtime: 0.3680102825164795 s

# Cirq (translate + their depth method)
Depth: 116869 (they always add 1 as the initial moment)
Runtime: 8.5937180519104 s
```

I we can compute "from scratch" the depth of a circuit of depth 100K with about 150K gates overall, with basically no extra memory used, I think we're good for a while? From here, 2 options:

Option 1: 100K moments for 20 qubits is at worst about `100k x 20 x 4 = 8M`of integer data + whatever python consumes to encapsulate, giving us access to all indices of each moment, but we're currently doing nothing with them and they're discarded at the end of the function. 8M is nothing and can be left around.

Option 2: I can actually completely get rid of that and just use the look up table: as a result the method becomes a whooping 5 lines of code, gives me an extra x2 speedup on this use case, and basically consumes 0 memory. But we no longer have moment indices at all.

Preference ? I think option 1 is already pretty badass, and if we decide that moments are important at least we can draw inspiration from these few lines, despite the data not being used really.

PR: https://github.com/goodchemistryco/Tangelo/pull/285/files

**Comment by AlexandreF-1qbit** [comment]
If this is fast enough, I don't really care if it is done automatically. More information is better.

Having the moments could be useful, and it does not seem to be very taxing on the memory with pretty big systems for classical simulation. I would also vote for that option.

**Comment by ValentinS4t1qbit** [comment]
It seems that with #285 , this has been solved.
