### ISSUE TITLE
[FEATURE REQUEST] Exporing a circuit to QASM or JSON as a sequence of Pauli Rotations

### ISSUE THREAD

**Issue by einarG-1qbit** [goodchemistryco/Tangelo#329]
Dear Tangelo devs,
Hope all is good. This is me agian :)

I'm trying to create a circuit for Hamiltonian simulation and then export the resulting gateset to QASM or json.
The problem is that when the circuit is exported to QASM its gates are decomposed into 1-qubit and 2-qubit rotation gates. What I need is a QASM or json file which consists of Pauli rotation  gates. For example, this is the description  I'm looking for:
```
[
    {"gate": "PauliRot", "param": 0.045321883918106265, "pauli_word": "YXXY", "wires": [0, 1, 2, 3]},
    {"gate": "PauliRot", "param": -0.045321883918106265, "pauli_word": "YYXX", "wires": [0, 1, 2, 3]}
]
```

Is there a way of getting a QASM or jason like the one above  from Tangelo?

Here is the code:
```
from tangelo import SecondQuantizedMolecule
from tangelo.toolboxes.qubit_mappings.mapping_transform import get_qubit_number, fermion_to_qubit_mapping
from tangelo.linq import Circuit, Gate
from tangelo.toolboxes.ansatz_generator.ansatz_utils import get_exponentiated_qubit_operator_circuit
from tangelo.linq.translator.translate_openqasm import translate_openqasm

# Molecule types: HH, C2HF3
molecule_name = "C2HF3"

if molecule_name == "C2HF3":
    molecule = [
        ("C", (0.0, 0.430631, 0.000000)),
        ("C", (-0.704353, -0.686847, 0.0)),
        ("F", (1.314791, 0.500587, 0.0)),
        ("F",(-0.554822, 1.630861, 0.0)),
        ("F", (-0.092517, -1.882156, 0.0)),
        ("H",(-1.780948, -0.706341, 0.0))   
    ]
elif molecule_name == "HH":
    molecule = [('H', (0, 0, 0)),('H', (0, 0, 0.74137727))]

second_quant_mol = SecondQuantizedMolecule(molecule, q=0, spin=0, basis="sto-3g")

hamiltonian = fermion_to_qubit_mapping(second_quant_mol.fermionic_hamiltonian, "JW")
circuit = get_exponentiated_qubit_operator_circuit(hamiltonian, time=0.5)

qasm_circuit_string = translate_openqasm(circuit)

# Write QASM file
qasm_file_name = f"./tangelo_qasm_circuits/circuit_molecule_{molecule_name}.qasm"
qasm_file_out = open(qasm_file_name, "w")
qasm_file_out.write(qasm_circuit_string)
qasm_file_out.close()
```

The code above works. It exports the QASM file but it breaks down the circuit into 1- and 2- qubit gates.

**Comment by AlexandreF-1qbit** [comment]
Hello @einarG-1qbit!

Better circuit exportation to qasm file is something we had noticed previously (#233). I have never encountered a use case where `PauliRot` is used in a qasm file, and I haven't found framework where this is supported.

The code below should do the job (I am using the most recent version of Tangelo). I think it is better to work directly with the `hamiltonian`, as the whole point of the `get_exponentiated_qubit_operator_circuit` function is to get a set of 1- and 2-qubit gates.
```python
import json

from tangelo import SecondQuantizedMolecule
from tangelo.toolboxes.qubit_mappings.mapping_transform import fermion_to_qubit_mapping

# Molecule types: HH, C2HF3
molecule_name = "C2HF3"
time = 0.5

if molecule_name == "C2HF3":
    molecule = [
        ("C", (0.0, 0.430631, 0.000000)),
        ("C", (-0.704353, -0.686847, 0.0)),
        ("F", (1.314791, 0.500587, 0.0)),
        ("F",(-0.554822, 1.630861, 0.0)),
        ("F", (-0.092517, -1.882156, 0.0)),
        ("H",(-1.780948, -0.706341, 0.0))
    ]
elif molecule_name == "HH":
    molecule = [('H', (0, 0, 0)),('H', (0, 0, 0.74137727))]

second_quant_mol = SecondQuantizedMolecule(molecule, q=0, spin=0, basis="sto-3g")

hamiltonian = fermion_to_qubit_mapping(second_quant_mol.fermionic_hamiltonian, "JW")

def pauli_word_to_dict(term, param):
    pauli_word = "".join(list(zip(*term))[1])
    wires = list(list(zip(*term))[0])
    return {"gate": "PauliRot", "param": param, "pauli_word": pauli_word, "wires": wires}

pauli_rotations = [pauli_word_to_dict(term, (coeff*time).real) for term, coeff in hamiltonian.terms.items() if term]

json_string = json.dumps(pauli_rotations, indent=4)

# Write json file
with open(f"./circuit_molecule_{molecule_name}.json", "w") as f:
    f.write(json_string )
```

However, there are some unknown on my end that you should be aware of:
- This is for an order=1 trotterization. If higher order is needed, it would require to take into account the recursive pattern of the trotterization (while also considering the proper handling of the `time` variable). The pattern would be the same as we do in https://github.com/goodchemistryco/Tangelo/blob/293f7610071536ebf0f95076629f74331a79b18e/tangelo/toolboxes/ansatz_generator/ansatz_utils.py#L84-L169
when `order!=1` and not calling the `exp_pauliword_to_gates` function to convert the pauli word to 1- and 2-qubit gates.
- I don't know what should be in the `param` slot: the R_z rotation angle or the pauli word coefficient when exponentiated? We use this formula https://github.com/goodchemistryco/Tangelo/blob/293f7610071536ebf0f95076629f74331a79b18e/tangelo/toolboxes/ansatz_generator/ansatz_utils.py#L68
after the coefficient has been multiplied with the `time` variable. In the code above, I just put the coefficient*time.
- The output format is not the very same as you posted. If this is a requirement, it is possible to output 1 python dictionary per line via [this example](https://stackoverflow.com/questions/47896877/json-save-one-dict-per-line).

**Comment by ValentinS4t1qbit** [comment]
From the perspective of someone pushing the development of Tangelo and trying to buy a useful suite of tools for the community, questions come to mind:

- should we offer functions that can help turning a Hamiltonian into a circuit ?
- should this support different output formats, through linq or directly built-in ?

Regardless of how @einarG-1qbit 's issue is solved, I think this conversation is an opportunity to form an opinion down the line. But first, let's see how we can solve this with what we have "on the shelf". :)

**Comment by JamesB-1qbit** [comment]
One thing to add. It is easy to account for higher Trotter order using `recursive_trotter_suzuki_decomposition`. Just change the line
```python3
pauli_rotations = [pauli_word_to_dict(term, (coeff*time).real) for term, coeff in hamiltonian.terms.items() if term]
```
to
```python3
from tangelo.toolboxes.ansatz_generator.ansatz_utils import recursive_trotter_suzuki_decomposition
pauli_words = list(hamiltonian.terms.items())
trotter_order = 2
pauli_rotations = [pauli_word_to_dict(term, coeff.real) for term, coeff in
                   recursive_trotter_suzuki_decomposition(pauli_words, order=trotter_order, time=time) if term]
```
If the desired trotter order is `trotter_order`. The currently supported trotter order is 1 (which is what was shown above by @AlexandreF-1qbit) or any even number.

**Comment by einarG-1qbit** [comment]
This is perfect! Thanks for timely replies and help!
