### ISSUE TITLE
Augment the Rotosolve optimizer to support Rotoselect

### ISSUE THREAD

**Issue by ValentinS4t1qbit** [goodchemistryco/Tangelo#386]
# Issue: Feature Request

The `Rotosolve` optimizer is a straightforward method to obtain the optimal value for a single qubit rotation in variational quantum algorithms. The current implementation in Tangelo supports its use in [ongoing research](https://arxiv.org/abs/2211.10501) involving the Qubit Coupled Cluster algorithm where typically only a single rotation axis is considered. This feature can be easily augmented to the `Rotoselect` optimizer, which chooses  both the optimal angle and axis of single qubit rotation.

- Paper describing Rotoselect: https://arxiv.org/pdf/1905.09692
- Implementation of Rotosolve in Tangelo: https://github.com/goodchemistryco/Tangelo/blob/main/tangelo/toolboxes/optimizers/rotosolve.py

**Describe the solution you'd like**

The solution would include a separate solver called `Rotoselect` which modifies the rotation axis (RX, RY, RZ) of the gates in the variational circuit. For each rotation axis, it could call `rotosolve_step` to find the optimal angle.

**Finish line**

Testing for this feature should be analogous to the [rotosolve tests](https://github.com/goodchemistryco/Tangelo/blob/main/tangelo/toolboxes/optimizers/tests/test_rotosolve.py).  The test would require an input variational circuit, and a Hamiltonian to minimize. These should be constructed such that the output optimized circuit has a different rotation axis for at least one rotation gate.

**Comment by cburdine** [comment]
Hi Valentin,

I'm here for UnitaryHack and thought this might be a good problem for me to tackle. Could you assign me to this issue? Thanks!

**Comment by ValentinS4t1qbit** [comment]
Game on, @cburdine ! Do your best :)

I recommend you work on something that has the desired behaviour and tries to reuse some `Rotosolve` code, and then ping @elloyd-1qbit and I to have a quick look at it and give you feedback. Then you should be able to have a clear checklist to take you to the finish line and earn the bounty :)

**Comment by ValentinS4t1qbit** [comment]
Solved by #392 by @cburdine
