### ISSUE TITLE
Adding support for accessing and modifying variational gates in ansatzes

### ISSUE THREAD

**Issue by cburdine** [goodchemistryco/Tangelo#399]
# Adding support for accessing and modifying variational gates in ansatzes

**What problem does this feature request help you overcome? Please describe.**

In [PR #392](https://github.com/goodchemistryco/Tangelo/pull/392) support was added for the Rotoselect optimizer, which modifies both the angle and axis of rotation for variational gates in a given ansatz. Currently, the Rotoselect algorithm can only be used by passing in a function of the form
```
def exp_rotoselect(var_params, var_rot_axes, ansatz, qubit_hamiltonian):
            ansatz.update_var_params(var_params)
            for i, axis in enumerate(var_rot_axes):
                ansatz.circuit._variational_gates[i].name = axis
            energy = sim.get_expectation_value(qubit_hamiltonian, ansatz.circuit)
            return energy
```
This function  requires the user to manually modify the protected member ansatz.circuit._variational_gates, which is not ideal.

**Describe the solution you'd like**
It would be great if we could add a better interface for modifying variational gates in ansatzes that does not require directly modifying the ansatz circuit.

I can think of two ways of implementing this. The most invasive approach would involve extending the interface of the `Ansatz` abstract class (in `tangelo.toolboxes.ansatz_generator.ansatz`) to include the functions `set_var_gates()` and `update_var_gates()`. Then, each ansatz object which extends the abstract Ansatz class will need to be modified to accommodate it in a manner that "makes sense" in the context of each ansatz.

**Describe alternatives you've considered**
Another (less invasive) approach could be to create some methods that directly modify the variational gates in a Circuit, while performing some basic validation. A method to retrieve all of the variational gates in a circuit would also be necessary. This would be much easier to implement, but would place the burden of updating gates in a meaningful way on the user.

**Additional context**
I am currently working on a solution along the lines of the first approach, but I am encountering some difficulties with handling certain ansatzes (such as UCCGD) where there appears to be a one-to-many mapping of variational parameters to variational gates. If we want to modify the axis of rotation of gates in these ansatzes, I suppose it would make sense to respect this one-to-many mapping so that certain symmetries of the ansatz wave function are preserved. I am also concerned that adding this feature to some ansatzes may be "non-physical" in the sense that certain canonical commutation relations will be violated. For example, some ansatzes contain parameterized exponentials of fermionic creation/annihilation operators mapped to pauli strings with the same CCRs. If we were to allow for arbitrary axes of rotation that violate these CCRs, would this be problematic? Should we add this feature for only some ansatzes and not others?

I would like to see if anyone has any ideas or recommendations for whether or not this feature should be added and how it can be done in a manner that is useful and physically meaningful. :atom_symbol:

**Comment by ValentinS4t1qbit** [comment]
@cburdine Thank you for taking the time to look into this !

To clarify, what modifications are we trying to enable for the user ? (gate names, or more ?)
> It would be great if we could add a better interface for modifying variational gates in ansatze that do not require directly modifying the ansatz circuit

Your observation highlighting that some ansatze have roots in physics is valid.  @alexfleury-sb may have some valuable insights on this.

For my 2 cents: I'm trying to put the user at the center of this, and weight the effort vs the gain

### What do we think is the gain ? 

Is it the satisfaction of not having to modify a private attribute directly ? Python's philosophy is "everyone is an adult" (e.g if you want to do something, we can't really stop you anyway). In 2 lines you've implemented something that hadn't been done before. I think it's kind of neat and one of the strengths of the simple `Circuit` data-structure in Tangelo (it would be a pain with some other packages).  

Can you both help me think a little bigger here, with maybe illustrations of how methods such as `set_var_gates` and `update_var_gates` could achieve ?

### What abut the cost ?

The cost seems non-trivial. Stuff needs to somehow work out with current ansatze but potentially future ones too, and everyone in this conversation I think has now experienced how cumbersome it is to make things work for every existing ansatze. If there's a smart way to handle these changes (additional "intermediary" ansatze classes to make inheritance do the heavy lifting or something for us ?), i think it's cool. If not, I'm worried that in terms of maintenance this makes things more complex than they already are.

**Comment by cburdine** [comment]
Thanks for the feedback, @ValentinS4t1qbit . Initially, my motivation for adding this feature was to provide an interface for our higher-level routines such as `VQESolver` to be compatible with optimizers such as `Rotoselect` that modify the gate axis of rotation.

Since `Rotoselect` is the only optimizer that requires this feature, I think it would be more prudent to wait and see if there is any demand for VQE to support optimizers that modify gate types in addition to gate parameters. I think the costs in this case outweigh any potential benefits. If this feature is added in the future, I think extending the Ansatz base class per @ValentinS4t1qbit 's recommendation is the best option here. Requiring all current and future ansatzes to have a `set_var_gates` and `update_var_gates` function seems to be too restrictive at the moment.
